more_books = [
  {:title => 'Shadow Captain', :genre => 'Science fiction', :description => 'Shadow Captain is a desperate story of cursed ships, vengeful corporations, and alien artifacts, of daring escapes and wealth beyond imagining ... and of betrayal.', :isnb_number => 9780316555708, :publish_date => '29-Jan-2019'},
  {:title => 'Tempt Me with Diamonds', :genre => 'Drama', :description => 'Rupert Lacey didn’t expect Diana to take the news without a fight. Still, he didn’t expect her to bring the battle directly to their newly shared doorstep—complete with a full set of trunks, and a full set of orders to the staff. ', :isnb_number => 9781420143607, :publish_date => '29-Jan-2018' },
  {:title => 'Fifty Shades Darker', :genre => 'Drama', :description => 'Daunted by the singular tastes and dark secrets of the beautiful, tormented young entrepreneur Christian Grey, Anastasia Steele has broken off their relationship. But desire for Christian still dominates her every waking thought, and when he proposes a new arrangement, Ana cannot resist. ', :isnb_number => 9780525431886 , :publish_date => '20-Jun-2017' },
  {:title => 'Blood AngelsmThe Complete Rafen Omnibus', :genre => 'Action and Adventure', :description => 'As the ashes settle on the devastating by civil war, the Blood Angels face a dire crisis and must call together their Successor Chapters or face extinction. But the sons of Sanguinius have many enemies, and this audacious scheme to rebuild their ranks comes under threat by the machinations of the arch-traitor Fabius Bile.', :isnb_number => 9781784968335, :publish_date => '10-Jan-2018' },
  {:title => 'Terran Tomorrow', :genre => 'Action and Adventure', :description => 'The diplomatic mission from Earth to World ended in disaster, as the Earth scientists discovered that the Worlders were not the scientifically advanced culture they believed. Though they brought a limited quantity of the vaccine against the deadly spore cloud, there was no way to make enough to vaccinate more than a few dozen. ', :isnb_number => 9780765390356, :publish_date => '13-Nov-2018' },
  {:title => 'Secret Desires of a Gentleman', :genre => 'Romance', :description => 'Once Upon a Time, Maria Martingale was going to elope. But Phillip Hawthorne, Marquess of Kayne, put a stop to those plans when he learned his younger brother intended to marry a cooks daughter.', :isnb_number => 9780061456824, :publish_date => '02-May-2017' },
  {:title => 'Carrie', :genre => 'Mystery', :description => 'An introverted girl with remarkable powers of telekinesis faces the horrors of teenage life and unleashes a few horrors of her own when she attends the high school prom.', :isnb_number => 9780307743664, :publish_date => '15-Jan-2016' },
  {:title => 'Sherlock Holmes and the Sussex Sea-Devils', :genre => 'Mystery', :description => 'It is the autumn of 1910, and for fifteen long years Sherlock Holmes and Dr John Watson have battled Rlluhloig, the Hidden Mind that was once Professor James Moriarty. Europe is creeping inexorably towards war, and a more cosmic conflict is nearing its zenith, as in a single night all the most eminent members of the Diogenes Club die horribly, seemingly by their own hands.', :isnb_number => 9781783295975, :publish_date => '13-Nov-2017' },
  {:title => 'The Green Mile', :genre => 'Horror', :description => 'The 1 New York Times bestselling dramatic serial novel and inspiration for the Oscar-nominated film of the same name starring Tom Hanks, the literary event (Entertainment Weekly) of The Green Mile is now available in its entirety. When The Green Mile first appeared, serialized as one volume per month, Stephen Kings The Green Mile was an unprecedented publishing triumph: all six volumes ended up on the New York Times bestseller delighted millions of fans the world over.', :isnb_number => 9780671041786, :publish_date => '06-Jun-2014' },
  {:title => 'The Stand (Complete and Uncut)', :genre => 'Horror', :description => 'A patient escapes from a biological testing facility, unknowingly carrying a deadly weapon: a mutated strain of super-flu that will wipe out 99 percent of the world’s population within a few weeks. Those who remain are scared, bewildered, and in need of a leader.', :isnb_number => 9780307743688, :publish_date => '07-Sep-2016' },
  
]

more_books.each do |book|
  Book.create!(book)
end